services:
  mysql:
    image: mysql:latest
    container_name: rrhh-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rrhh-root-password
      MYSQL_USER: rrhh-user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: rrhh
    ports:
      - "9001:3306"
    volumes:
      - rrhh-mysql-data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: rrhh-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rrhh-root-password
    ports:
      - "9000:80"
    depends_on:
      - mysql

volumes:
  rrhh-mysql-data: