name: 🚀 Deploy por FTP, borrar caché y npm install

on:
  push:
    branches:
      - main  # Se ejecuta cuando hay cambios en main

jobs:
  ftp-deploy-and-install:
    name: 📂 Subir archivos, borrar caché y ejecutar npm install
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Descargar el código
        uses: actions/checkout@v4

      - name: 📤 Subir archivos por FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          local-dir: ./
          server-dir: /CoreERP/Backend/
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/*
            **/*.md
          dry-run: false

      - name: 🧹 Borrar caché y ejecutar npm install
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd www/Karlos/CoreERP/Backend/
            rm -rf node_modules
            npm cache clean --force
            npm install